### ISSUE TITLE
market crashes on restoreTransactions()

### ISSUE THREAD

**Issue by lorenx** [robotmedia/AndroidBillingLibrary#37]
on first run i call:

```
BillingController.restoreTransactions(mActivity);
```

transactions are restored correctly but a popup appears sayng that the market have just crashed.
from logcat:

```
java.lang.IllegalArgumentException: Type mismatch type:null tag:1
 at com.google.common.io.protocol.ProtoBuf.assertTypeMatch(ProtoBuf.java:897)
 at com.google.common.io.protocol.ProtoBuf.insertObject(ProtoBuf.java:1022)
 at com.google.common.io.protocol.ProtoBuf.insertString(ProtoBuf.java:827)
 at com.google.common.io.protocol.ProtoBuf.addString(ProtoBuf.java:173)
 at com.android.vending.model.AckNotificationsRequest.addNotificationId(AckNotificationsRequest.java:40)
 at com.android.vending.util.AlarmService$AsynchAckNotifications.doRequest(AlarmService.java:274)
 at com.android.vending.billing.MarketBillingService$AsynchInAppAckNotifications.doRequest(MarketBillingService.java:640)
 at com.android.vending.AsynchRequestRunner$RequestRunnable.run(AsynchRequestRunner.java:37)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
 at java.lang.Thread.run(Thread.java:1019)
 at com.android.vending.AsynchRequestRunner$VendingThreadFactory$VendingFactoryThread.run(AsynchRequestRunner.java:118)
```

**Comment by lorenx** [comment]
ok, i solved this way.

previously i had:

```
BillingController.requestPurchase(mActivity, productId);

//...

public void onPurchaseStateChanged(String productId, PurchaseState purchaseState) {
    BillingController.confirmNotifications(mActivity, productId);
}
```

now i changed it to:

```
BillingController.requestPurchase(mActivity, productId, true);

//...

public void onPurchaseStateChanged(String productId, PurchaseState purchaseState) {
    if (!purchaseState.equals(PurchaseState.PURCHASED)) {
        BillingController.confirmNotifications(mActivity, productId);
    }
}
```

i thought they behaved the same, could i ask how they differ?
thank you.

**Comment by codeslicer** [comment]
I'm having similar issues. In onPurchaseStateChanged(...) I run BillingController.confirmNotifications(...). Unfortunately if these methods run as a result of restoreTransacrions(), I get a crash.

08-17 00:44:18.933: ERROR/AndroidRuntime(7698): java.lang.RuntimeException: Unable to start service net.robotmedia.billing.BillingService@47bd8de0 with Intent { act=com.myapp..CONFIRM_NOTIFICATIONS cmp=com.myapp/net.robotmedia.billing.BillingService (has extras) }: java.lang.NullPointerException
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3063)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.app.ActivityThread.access$3600(ActivityThread.java:125)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.os.Handler.dispatchMessage(Handler.java:99)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.os.Looper.loop(Looper.java:123)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.app.ActivityThread.main(ActivityThread.java:4627)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at java.lang.reflect.Method.invokeNative(Native Method)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at java.lang.reflect.Method.invoke(Method.java:521)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at dalvik.system.NativeStart.main(Native Method)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698): Caused by: java.lang.NullPointerException
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.os.Parcel.readException(Parcel.java:1266)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.os.Parcel.readException(Parcel.java:1248)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at com.android.vending.billing.IMarketBillingService$Stub$Proxy.sendBillingRequest(IMarketBillingService.java:100)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at net.robotmedia.billing.request.BillingRequest.run(BillingRequest.java:79)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at net.robotmedia.billing.BillingService.runRequest(BillingService.java:224)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at net.robotmedia.billing.BillingService.runRequestOrQueue(BillingService.java:238)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at net.robotmedia.billing.BillingService.confirmNotifications(BillingService.java:119)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at net.robotmedia.billing.BillingService.handleCommand(BillingService.java:189)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at net.robotmedia.billing.BillingService.onStartCommand(BillingService.java:169)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3053)
08-17 00:44:18.933: ERROR/AndroidRuntime(7698):     ... 10 more

EDIT: This looks like Issue #32.

**Comment by robotmedia** [comment]
@lorenx Thanks for the report! We'll check this out shortly.

**Comment by lorenx** [comment]
for me, you can merge this issue with #28, thank you.

**Comment by larsa71** [comment]
Hi,

sorry for putting a comment on an already closed issue but:

just went through the different issues and I think that this issue is not solved for manual confirmations. Correct me if I am wrong but a restore transactions will not provide a notification id. Hence, it should not internally in the BillingController be added to the manual confirmation array at all?

So a suggestion instead of this:

```
public static void onSignatureValidateResult(Context context, String signedData, String signature, boolean validationSuccessful) {
```

.
.
        for (Transaction p : purchases) {
            if (p.notificationId != null && automaticConfirmations.contains(p.productId)) {
                confirmations.add(p.notificationId);
            } else {
                // TODO: Discriminate between purchases, cancellations and
                // refunds.
                addManualConfirmation(p.productId, p.notificationId);
            }
            storeTransaction(context, p);
            notifyPurchaseStateChange(p.productId, p.purchaseState);
        }
.
.

It could be something like this and in the notifyPurchaseStateChange callback the BillingController.confirmNotifications call would not matter in this case as it will not find the item in the manual confirmation list:

```
public static void onSignatureValidateResult(Context context, String signedData, String signature, boolean validationSuccessful) {
```

.
.

```
    for (Transaction p : purchases) {
        if (p.notificationId != null) {
            if (automaticConfirmations.contains(p.productId)) {
                confirmations.add(p.notificationId);
            } else {
                // TODO: Discriminate between purchases, cancellations and
                // refunds.
                addManualConfirmation(p.productId, p.notificationId);
            }               
        }

        storeTransaction(context, p);
        notifyPurchaseStateChange(p.productId, p.purchaseState);
    }
```

.
.
.
