### ISSUE TITLE
Is there any problem to call restoreTransactions on every app load?

### ISSUE THREAD

**Issue by budius** [robotmedia/AndroidBillingLibrary#94]
Hi,

thank you very much for the library, made the billing development a breeze.

This post is just a support request.
The app I'm developing is VERY likely to be used on more than one device by user (because connect devices together) and through an in-app purchase it enables the full features.

Currently the app calls `BillingController.restoreTransactions(context);` only on the first run.
But if (when) the user purchase the upgrade on a device 1, he won't see it on device 2 unless he uninstall/re-install the app.

So I ask, if I simply call it every single time the app loads, will there be any problem with the database that is storing the transaction or will just drop the DB and re-populate and that's it?

thanks.

**Comment by thisisnottheaccountyourelookingfor** [comment]
Google's docs specifically request not calling restoreTransactions frequently due to load.

User managed purchases and subscriptions will eventually show up on the other devices.  It seems to be whenever the next time Google Play pings their server.  I've never timed it, but the last time I tried it didn't happen within a few minutes.  When I checked later it was updated, but I don't know how long it took.  Google Play app doesn't appear to be using cloud messaging for this yet.  If you want something real-time I would just consider adding an ability to have the user manually restore transactions or implement cloud messaging within your app to send a notification to other devices to update.

**Comment by hpique** [comment]
Yes, as @jgilbert42 points out, an option to manually restore transactions might be the safest solution.

**Comment by budius** [comment]
hi, thanks for the reply and sorry for commenting on a closed question, but users usually are keen to complain if things don't happen automagically.

I do understand what you say about not calling it too frequent, and it does makes perfect sense.
Based on that I could put some sort of limitation, such as (not more than once a day) for example.

But my initial question was not answered, will it cause any trouble to the SQLite database that the library is managing if I call it more than once? For example, if I call it every time the main activity is loaded but not more than once a day. Will it create duplicate entry, or something weird, or will it play nice and just update the current rows?

**Comment by hpique** [comment]
No, there shouldn't be any duplicate entries or weird behavior, and as far as I know there haven't been any reports that indicate otherwise.

**Comment by budius** [comment]
Thank you again for the support and thank you very very much again for the library  =]
